extends: ['@commitlint/config-conventional']
header-max-length: [0, "always", 72]
body-leading-blank: [0, "always"]
footer-leading-blank: [1, "always"]
scope-case: [2, "always", "lower-case"]
subject-case: [2, "never", ["sentence-case", "start-case", "pascal-case", "upper-case"]]
subject-empty: [2, "never"]
subject-full-stop: [2, "never", "."]
type-case: [2, "always", "lower-case"]
type-empty: [2, "never"]